# Generated by Django 3.2.6 on 2021-11-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
